### ISSUE TITLE
Tokenize contributors

### ISSUE THREAD

**Issue by Mick00** [Mick00/carfax-on-blockchain#1]
Tokenize the contributors by making a contract that inherits https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol

Functionnality:

- The tokenURI() must be an IPFS hash that will point to the metadata about the the contributors
- A registrar will call the method register(ipfsHash: bytes, address: minter) to put an identity in awaiting confirmation state
- Once the registrar has registered the contributor, the contributor can call confirmRegistration(registrarAddress: address) and it will mint the NFT representing it's contributor identity
- The contract will have a way to query the waitingForConfirmation identity
- The contract will throw an event for the registration and the confirm registration
- burn(id: number): burns the contributor's NFT, can only be called by registrar

![image](https://user-images.githubusercontent.com/20918417/170519620-3741846e-e434-40c7-b308-e004459d48bb.png)

**Comment by mOGrs** [comment]
@Mick00 Desole pour tous les questionnements mais je trouve tu es un bon project owner ;) 

Est-ce qu'on lock le register ? Une fois la transaction send, tu peux pas edit le hash. On fait une function edit register ?

Dans la meme lancer, si le garage change de nom ou quelconque info, il devrait faire la demande au registar pour changer le URI. Une double validation ?
Le contributor register une modification. Le registar confirm une modification.

**Comment by Mick00** [comment]
Thanks man! Pas de problème pour les questions on se demelent ensemble.

Si par lock le register tu veux dire ne pas permettre de modification, oui.

J’avais pas pensé à l’edit, mais oui, il faut refaire le processus de validation et update l’uri du nft au lieu de mint



Le 31 mai 2022 à 07:59, mOGrs ***@***.***> a écrit :

﻿

@Mick00<https://github.com/Mick00> Desole pour tous les questionnements mais je trouve tu es un bon project owner ;)

Est-ce qu'on lock le register ? Une fois la transaction send, tu peux pas edit le hash. On fait une function edit register ?

Dans la meme lancer, si le garage change de nom ou quelconque info, il devrait faire la demande au registar pour changer le URI. Une double validation ?
Le contributor register une modification. Le registar confirm une modification.
